# Generated by Django 3.0.1 on 2020-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200105_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
